# -*- coding: utf-8 -*-
"""Jogo de Nim

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d1kF9FxP1aOpJ-wvp4jKhOMfYn-V7QvB
"""

#JOGO DO NIM
def partida():
  n = int(input("Quantas peças? "))
  m = int(input("Limite de peça por jogada? "))
  while m>= n or m<=0:
    m = int(input("Limite de peça por jogada? "))
  vezPc = False
  if n%(m+1) == 0:
    print("-"*50)
    print("Você começa!")
  else:
    print("Computador começa!")
    vezPc = True
  while n > 0:
    if vezPc:
      y = computador_escolhe_jogada(n, m)
      n = n - y
      if y == 1:
        print("O computador tirou somente uma peça.")
      else:
        print(f"O computador tirou {y} peças.")
      if n == 1:
        print("Agora resta apenas uma peça no tabuleiro.")
      else:
        print(f"Agora restam {n} peças.")
      print("-"*50)
      vezPc = False
    else:
      x = usuario_escolhe_jogada(n,m)
      n = n - x
      if x == 1:
        print("Você tirou somente uma peça. ")
      else:
        print(f"Você tirou {x} peças.")
      if n == 1:
        print("Agora resta apenas uma peça no tabuleiro.")
      else:
        print(f"Agora restam {n} peças.")
      vezPc = True 

  print("Fim do jogo! O computador ganhou!")


def computador_escolhe_jogada(n, m):
  print("-"*50)
  print("Vez do computador.")
  if n <= m:
    return n 
  else: 
    resultado = n % (m+1)
    if resultado > 0:
      return resultado 
    return m  

def usuario_escolhe_jogada(n,m):
  pergunta = int(input("Quantas peças você vai tirar? "))
  while pergunta> m or pergunta <= 0:
    print()
    print("Oops! Jogada inválida! Tente de novo.")
    print()
    pergunta = int(input("Quantas peças você vai tirar? "))
  return pergunta

def campeonato():
  numero_rodada = 1
  placar = 0 
  while numero_rodada <= 3:
    print()
    print("**** Rodada", numero_rodada, "****")
    print()
    partida()
    numero_rodada += 1
    placar += 1
    print()
    print(f"Placar: Você 0 X {placar} Computador")

  
print("BEM-VINDO AO JOGO DE NIM!!!")
regras = input("Você deseja ler as regras? s/n: ").lower()
while regras.lower() not in {'s', 'n'}:
  print("Por favor, responda apenas com s ou n!")
  regras = input("Você deseja ler as regras? s/n: ")
if regras == "s":
  print("-"*50)
  print("O jogo é jogado em duplas, as jogadas são feitas alternadamente, \ne cada jogador deve retirar uma quantidade de palitos, \ndentre um total que varia de acordo com o combinado entre os jogadores. \nO ganhador é aquele que retirar o último palito da mesa.")
print("-"*50)
print("1. Para jogar apenas uma rodada.")
tipo_partida = int(input("2. Para jogar um campeonato.\n"))

if tipo_partida == 2:
  print("-"*50)
  print("Você escolheu campeonato!")
  print("-"*50)
  campeonato()
else:
  if tipo_partida == 1:
    print("-"*50)
    print("Você escolheu uma rodada só. Vamos nessa!")
    partida()